name: Publish tests summary

on:
  workflow_call:
    inputs:
      runner:
        description: Label of the runner specified in Build workflow
        required: true
        type: string

jobs:
  publish-test-summaries:
    name: Start testing
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Publish tests summary
        uses: phoenix-actions/test-reporting@v15
        if: success() || failure()
        with:
          artifact: twister_out_xml_files_artifacts
          name: Zephyr test summary
          path: '*.xml'
          reporter: java-junit
          output-to: step-summary