name: Publish tests summary
on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  publish-test-summaries:
    runs-on: self-hosted
    steps:
      - name: Test Report
        uses: phoenix-actions/test-reporting@v15
        if: success() || failure()
        with:
          artifatcts: test_artifacts
          name: Firmware Test Summary
          path: 'test-summary/*.xml'
          reporter: java-junit
          output-to: step-summary