name: Publish summary of all test
on:
  workflow_call:

jobs:
  publish-test-summaries:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Gather summaries
        uses: actions/download-artifact@v4
        continue-on-error: true
        if: always()
        with:
          name: Test summary
          path: test-summary
          pattern: samples-zephyr-*
          merge-multiple: true
          include-hidden-files: true
          if-no-files-found: error
          retention-days: 5

      - name: Test Report
        uses: phoenix-actions/test-reporting@v15
        if: success() || failure()
        with:
          name: Firmware Test Summary
          path: test-summary/*.xml
          reporter: java-junit
          output-to: step-summary