name: Publish tests summary
on:
  workflow_call:
    inputs:
      runner:
        description: Label of the runner specified in Build workflow
        required: true
        type: string

jobs:
  publish-test-summaries:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Test Report
        uses: phoenix-actions/test-reporting@v15
        if: success() || failure()
        with:
          artifact: summary_test_artifacts
          name: Zephyr test summary
          path: '*.xml'
          reporter: java-junit
          output-to: step-summary