name: Testing

on:
  workflow_call:
    inputs:
      docker_image:
        description: Docker image to use in tests
        required: true
        type: string
      runner_label:
        description: Label of the runner specified in Build workflow
        required: true
        type: string
      board_target:
        description: Target board for the build
        required: true
        type: string
      test_hardware:
        description: Tests target
        required: true
        type: string
      test_tag:
        description: Test TAGs to filter tests
        required: false
        type: string
      pytest_args:
        description: Arguments to the pytest subprocess (extend YAML config)
        required: false
        type: string
      test_scenario:
        description: Test suite scenario to run
        required: false
        type: string
      tests_target:
        description: Tests scope to run
        required: true
        default: app/repo/shell
        type: string
      integration_tests:
        description: Condition to run integration tests only
        required: false
        type: string

env:
  # Pass all secrets as json to jobs
  SECRETS_JSON: ${{ toJSON(secrets) }}

jobs:
  testing:
    name: Start testing
    runs-on: ${{ inputs.runner_label }}
    outputs:
      test_type: ${{ inputs.tests_target }}
      label: ${{ inputs.runner_label }}
    defaults:
      run:
        working-directory: customer-application
    container:
      image: ${{ inputs.docker_image }}
      options: >
        --device=/dev/ttyUSB0 
        --privileged
        -v /var/run/dbus:/var/run/dbus 
        -v /run/dbus:/run/dbus 
        -v /dev:/dev
        -v /etc/udev/rules.d:/etc/udev/rules.d
        -e DBUS_SESSION_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: customer-application
      
      # Initiate Zephyr environment
      - name: Initialize
        shell: bash
        run: |
            echo "Checking out Zephyr env..."
            pwd
            echo "Current github workspace:"
            ls -la
            echo "Parent github folder"
            ls -la ..
            rm -rf ../.west
            west init -l .
            west update -o=--depth=1 -n
            west blobs fetch hal_espressif
            
      # Install lib extras for testing
      - name: Install lib extras
        shell: bash
        run: |
            sudo apt-get update
            sudo apt-get install -y iperf
            sudo apt-get install -y sysbench fio
            sudo apt-get install -y curl
            sudo apt-get install -y udev            
            sudo apt-get install -y python3-dev
            sudo apt-get install -y golang-go            
            sudo apt-get install -y udev
            sudo udevd --daemon


      # Install Python extras for testing
      - name: Install Python extra packages
        shell: bash
        run: |
            pip install -r requirements-extras.txt

      # Setup for tools
      - name: Setup for test tools
        shell: bash
        run: |
            go install github.com/apache/mynewt-mcumgr-cli/mcumgr@latest
            sudo setcap cap_net_raw,cap_net_admin+eip ~/go/bin/mcumgr

      #  Review of variables from Build workflow
      - name: Show variables from caller workflow
        shell: bash
        run: |
            echo "Variables from caller workflow:"
            echo "docker_image: ${{ inputs.docker_image }}"
            echo "runner_label: ${{ inputs.runner_label }}"
            echo "integration_tests: ${{ inputs.integration_tests }}"
            echo "board_target: ${{ inputs.board_target }}"
            echo "tests_target: ${{ inputs.tests_target }}"
            echo "test_scenario: ${{ inputs.test_scenario }}"
            echo "test_tag: ${{ inputs.test_tag }}"
            echo "pytest_args: ${{ inputs.pytest_args }}"
            echo "test_hardware: ${{ inputs.test_hardware }}"
            
      # Generate list of all tests in application in txt-format
      - name: Create list of all application tests
        shell: bash
        run: python .github/scripts/tests_yaml_parser.py

      # Generate tests paths to run with twister command
      - name: Create test list with tests scope
        shell: bash
        # No test scenario is filtered
        if : ${{ inputs.test_scenario == 'N/A' || '' }} 
        run: python .github/scripts/get_tests_list.py --tests_scope ${{ inputs.tests_target }}

      - name: Create test list with test scenario
        shell: bash
        # Specific test scenario is filtered
        if : ${{ inputs.test_scenario != 'N/A' || '' }} 
        run: python .github/scripts/get_tests_list.py --tests_scenario ${{ inputs.tests_target }} 
        
      - name: Create test list with robot tests
        shell: bash
        # Specific test scenario is filtered
        if : ${{ inputs.tests_target == 'app/robot' }} 
        run: python .github/scripts/get_tests_list.py --tests_robot ${{ inputs.tests_target }} 

      # Put list of testcases into output variable for shell script usage
      - name: Get tests list
        shell: python
        id: py-script
        run: |
            import os
            import re
            regex = re.compile('.*_tests.txt')
            for dir in os.listdir('.'):
                if regex.match(dir):
                  with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
                    f.write(f'test_list={os.path.join(dir)}\n')

      # Pass secrets for tests into json file
      - name: Create json file with secrets variables
        shell: bash
        run: |
            echo $SECRETS_JSON > vars.json
            cat vars.json

      # Auto mapping of USB ports to udev rules
      - name: Auto mapping of USB ports to udev rules
        shell: bash
        if : ${{ inputs.test_hardware == 'Real_hardware' }} 
        run: |
            echo "Check the udev daemon is running..."
            sudo service udev status
            sudo chmod +x .github/scripts/udev_mapping_serial_ports.sh
            .github/scripts/udev_mapping_serial_ports.sh ${{ inputs.board_target }}



      # Teardown: remove udev file from host machine with serial ports mapping
      - name: Remove udev file with serial ports mapping
        shell: bash
        if : ${{ inputs.test_hardware == 'Real_hardware' }} 
        run: |
            echo "Check list of the udev files..."
            sudo ls -la /etc/udev/rules.d
            sudo chmod +x .github/scripts/remove_udev_mapping_serial_ports.sh
            .github/scripts/remove_udev_mapping_serial_ports.sh
